# This file was generated by GoReleaser. DO NOT EDIT.
cask "ajaj" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "9c6933aa5d78e19825b9b991ff946f550fa4a9d248c819181f97ce7e05afdfcb"
      url "https://github.com/up2jj/ajaj/releases/download/v#{version}/ajaj_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c847c3a39c2d11eea04070aab2ed90fad66beb47fb7ac908951a387e185ff011"
      url "https://github.com/up2jj/ajaj/releases/download/v#{version}/ajaj_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "ajaj"
  desc "Switch between isolated Claude Code and Codex account profiles"
  homepage "https://github.com/up2jj/ajaj"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ajaj"
  bash_completion "completions/ajaj.bash"
  fish_completion "completions/ajaj.fish"
  zsh_completion "completions/ajaj.zsh"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ajaj"]
  end

  # No zap stanza required

end
