# This file was generated by GoReleaser. DO NOT EDIT.
cask "ajaj" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "991a86de3a311201b399eddcdc6a92158ef09a02fb52ab23f0dc37dcf98e6468"
      url "https://github.com/up2jj/ajaj/releases/download/v#{version}/ajaj_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "af427ac698e311f7fdc12ed73f0da2d3108d59321d4a2d718f7844adb3589e7b"
      url "https://github.com/up2jj/ajaj/releases/download/v#{version}/ajaj_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "ajaj"
  desc "Switch between isolated Claude Code and Codex account profiles"
  homepage "https://github.com/up2jj/ajaj"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ajaj"
  bash_completion "completions/ajaj.bash"
  fish_completion "completions/ajaj.fish"
  zsh_completion "completions/ajaj.zsh"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ajaj"]
  end

  # No zap stanza required

end
