# This file was generated by GoReleaser. DO NOT EDIT.
cask "ajaj" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "2d9100c6c179a317d4efc572e4e937d0224aecda6422d0e3829d69f3109c4a24"
      url "https://github.com/up2jj/ajaj/releases/download/v#{version}/ajaj_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ac405672f27f1c86c8f71cc310cdece535cfe5358c2ef21846853d6705d26874"
      url "https://github.com/up2jj/ajaj/releases/download/v#{version}/ajaj_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "ajaj"
  desc "Switch between isolated Claude Code and Codex account profiles"
  homepage "https://github.com/up2jj/ajaj"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ajaj"
  bash_completion "completions/ajaj.bash"
  fish_completion "completions/ajaj.fish"
  zsh_completion "completions/ajaj.zsh"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ajaj"]
  end

  # No zap stanza required

end
