# This file was generated by GoReleaser. DO NOT EDIT.
cask "kbrd" do
  version "0.9.0"

  on_macos do
    on_intel do
      sha256 "ddad2c41cca77652b09213acba76588c6680684eabf5a193d90337c690356131"
      url "https://github.com/up2jj/kbrd/releases/download/v#{version}/kbrd_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e1d09049c5ed642ea55dbcdaf1627b37c8f6a6a3ff9e7b7fd0af24fed9a6fe36"
      url "https://github.com/up2jj/kbrd/releases/download/v#{version}/kbrd_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "kbrd"
  desc "Terminal-based, keyboard-driven Kanban board"
  homepage "https://github.com/up2jj/kbrd"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kbrd"
  bash_completion "completions/kbrd.bash"
  fish_completion "completions/kbrd.fish"
  zsh_completion "completions/kbrd.zsh"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kbrd"]
  end

  # No zap stanza required

end
