# This file was generated by GoReleaser. DO NOT EDIT.
cask "kbrd" do
  version "0.13.0"

  on_macos do
    on_intel do
      sha256 "c923c434743be4b4182c6cd185f84230d13f80a59914f41d1fe1462b6560055f"
      url "https://github.com/up2jj/kbrd/releases/download/v#{version}/kbrd_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "80a232ae8b67d428bad18346a9fff1f6ade3fc1574ba4365b9d037c8463065e5"
      url "https://github.com/up2jj/kbrd/releases/download/v#{version}/kbrd_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "kbrd"
  desc "Terminal-based, keyboard-driven Kanban board"
  homepage "https://github.com/up2jj/kbrd"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kbrd"
  bash_completion "completions/kbrd.bash"
  fish_completion "completions/kbrd.fish"
  zsh_completion "completions/kbrd.zsh"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kbrd"]
  end

  # No zap stanza required

end
