# This file was generated by GoReleaser. DO NOT EDIT.
cask "kbrd" do
  version "0.24.0"

  on_macos do
    on_intel do
      sha256 "6ebb61fa8f42682d684c813007a5443c26f427de8a43a911bcd85a3bdf97d2e9"
      url "https://github.com/up2jj/kbrd/releases/download/v#{version}/kbrd_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1240a54c33a8d0df96bce4185cfafb1b0b6d07968625d023f98417a6d8cbf0f8"
      url "https://github.com/up2jj/kbrd/releases/download/v#{version}/kbrd_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "kbrd"
  desc "Terminal-based, keyboard-driven Kanban board"
  homepage "https://github.com/up2jj/kbrd"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kbrd"
  bash_completion "completions/kbrd.bash"
  fish_completion "completions/kbrd.fish"
  zsh_completion "completions/kbrd.zsh"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kbrd"]
  end

  # No zap stanza required

end
