# This file was generated by GoReleaser. DO NOT EDIT.
cask "wuko" do
  version "0.8.0"

  on_macos do
    on_arm do
      sha256 "6bbaa18208b8501d038b577a4cf90da392bdc0e4f2930e81150bbbdb7d0286ce"
      url "https://github.com/up2jj/wuko/releases/download/v#{version}/wuko_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "18c6f8aaa6f9abd5d6acf6e1cef0c60453ca8a261bc1e6b8c93b52234e2ae36e"
      url "https://github.com/up2jj/wuko/releases/download/v#{version}/wuko_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "538e11f30ae6c42d23098bc2765a39604f3da4ddd70df1afedfc208597ec43cd"
      url "https://github.com/up2jj/wuko/releases/download/v#{version}/wuko_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "63ab33a963f2b27e7ca464cc17d204ea16097f849694e4576b0374c253d1f028"
      url "https://github.com/up2jj/wuko/releases/download/v#{version}/wuko_#{version}_linux_amd64.tar.gz"
    end
  end

  name "wuko"
  desc "Trusted workflow runner for everyday development tasks"
  homepage "https://github.com/up2jj/wuko"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wuko"
  bash_completion "completions/wuko.bash"
  fish_completion "completions/wuko.fish"
  zsh_completion "completions/wuko.zsh"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wuko"]
  end

  # No zap stanza required
end
