# This file was generated by GoReleaser. DO NOT EDIT.
cask "wuko" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "6554ac16647d202fdc4471698b2a17aebdaead8550b8c06a84469ec57d98bf29"
      url "https://github.com/up2jj/wuko/releases/download/v#{version}/wuko_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "78d03b44421c37241cdfe2b0730866ebecef5f15f007c25892822989e22277bf"
      url "https://github.com/up2jj/wuko/releases/download/v#{version}/wuko_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "eeaf4ad143add311583a64c8059e7f45e1a809364fd993f5e6d68808824f2918"
      url "https://github.com/up2jj/wuko/releases/download/v#{version}/wuko_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3191b29f406884c8fb476f3122d30b833ce3279f464a9a0967313b27d6e2d93a"
      url "https://github.com/up2jj/wuko/releases/download/v#{version}/wuko_#{version}_linux_arm64.tar.gz"
    end
  end

  name "wuko"
  desc "Trusted workflow runner for everyday development tasks"
  homepage "https://github.com/up2jj/wuko"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wuko"
  bash_completion "completions/wuko.bash"
  fish_completion "completions/wuko.fish"
  zsh_completion "completions/wuko.zsh"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wuko"]
  end

  # No zap stanza required

end
