# This file was generated by GoReleaser. DO NOT EDIT.
cask "wuko" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/wuko"]
    end
  end

  version "0.15.0"

  on_macos do
    on_arm do
      sha256 "80cf0b03d4b16ac93f5d2f9cf9781dd11211ae67afda12c84037bcee10aad945"
      url "https://github.com/up2jj/wuko/releases/download/v#{version}/wuko_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c8fb71a88729eb59a4b3ad0c69555c54c8d603ea78ea996c55b9c5e7529dadab"
      url "https://github.com/up2jj/wuko/releases/download/v#{version}/wuko_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d0691368055b3a3557e3f8ece79acd0dc8bbc119740213fed3477e5efd8b6d22"
      url "https://github.com/up2jj/wuko/releases/download/v#{version}/wuko_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f27deef445a649495d244ac3ba08f3ff999fb1964436fade0583bd10ba66e5fe"
      url "https://github.com/up2jj/wuko/releases/download/v#{version}/wuko_#{version}_linux_amd64.tar.gz"
    end
  end

  name "wuko"
  desc "Trusted workflow runner for everyday development tasks"
  homepage "https://github.com/up2jj/wuko"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wuko"
  bash_completion "completions/wuko.bash"
  fish_completion "completions/wuko.fish"
  zsh_completion "completions/wuko.zsh"

  # No zap stanza required
end
